server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/seats
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update # For development, consider 'none' or 'validate' for production
    open-in-view: false
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: false # Disable H2 console

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui